# Generated by Django 5.2.8 on 2025-11-14 15:11

import Donations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=5)),
                ('isrecurring', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(blank=True, default=Donations.models.get_anonymous_user, null=True, on_delete=models.SET(Donations.models.get_anonymous_user), related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
