# Generated by Django 5.2.8 on 2025-11-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donations', '0002_rename_isrecurring_donation_is_recurring'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='impact_pathway_slug',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
